<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MiKiNuo.Mvi.Platforms.Avalonia" Version="0.3.5" />
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DshDesktop.Application\DshDesktop.Application.csproj" />
    <ProjectReference Include="..\DshDesktop.Domain\DshDesktop.Domain.csproj" />
  </ItemGroup>
</Project>
